export const GETHOBBIES= 'GETHOBBIES';
export const GETLANGUAGES= 'GETLANGUAGES';
export const GETEDUCATIONS= 'GETEDUCATIONS';
export const GETEXPERIENCE= 'GETEXPERIENCE';
export const GETPROJECTS= 'GETPROJECTS';
export const GETSKILLS= 'GETSKILLS';
export const GETCONTACT= 'GETCONTACT';
export const GETABOUT= 'GETABOUT';

export const STARTLOADING= 'STARTLOADING';
export const ENDLOADING= 'ENDLOADING';

export const SHOWALERT= 'SHOWALERT';
export const HIDEALERT= 'HIDEALERT';